### ISSUE TITLE
Support for workflow 3.x dependency

### ISSUE THREAD

**Issue by agirling** [geekq/workflow-activerecord#14]
Requesting support for `workflow` 3.x series, for Ruby 3 support.  Gemspec is currently limiting to `workflow ~> '2.0'`

Reference: https://github.com/geekq/workflow/pull/228

**Comment by geekq** [comment]
Released [workflow-activerecord 6.0.0 ](https://rubygems.org/gems/workflow-activerecord/versions/6.0.0), retired old Ruby, Rails versions, switched to workflow 3.x
