### ISSUE TITLE
Perform the transition in a transaction

### ISSUE THREAD

**Issue by romanbsd** [geekq/workflow-activerecord#16]
Good day,
I'm usually prepending the following module in order to have the state transition performed in a transaction, so both the state and other changed attributes are atomically modified. I think others can also benefit from this approach.
```ruby
  module TransitionTransaction
    def process_event!(name, *, **)
      transaction { super(name, *, **) }
    end
  end
```
If there is some interest to incorporate this in workflow-activerecord, I can make a PR. Alternatively I can add it to documentation.

**Comment by geekq** [comment]
Yes, lets add it to documentation!
Please briefly describe

1. the motivation: when somebody needs / should use it
2. how exactly to use it. You define the `TransitionTransaction` module and then include the module in the model class?
