### ISSUE TITLE
Call on_*_entry for initial state

### ISSUE THREAD

**Issue by hinrik** [geekq/workflow-activerecord#6]
I was updating an old Rails application from using `acts_as_state_machine` to using `workflow`, and I ran into the issue that workflow does not run `on_*_entry` hooks for the initial state, unlike AASM. I had to emulate it with the following:

``` ruby
after_create :on_active_entry

# parameters made optional to work with after_create
def on_active_entry(new_state = nil, event = nil)
    self.something = "foobar"
    self.save if persisted?
end
```

Can workflow be modified to consistently run the `on_*_entry` hook for every state entered, including the inital one?

**Comment by avk** [comment]
I just ran into this issue as well when using workflow for an Invite model. I wanted to handle invites to existing users and thought that an on_entry into the initial state would be the most logical place to do so.

**Comment by gastonmorixe** [comment]
:+1:

**Comment by geekq** [comment]
Just realized: there is no way for an included module like `Workflow` to hook into _generic_ Ruby object creation. So the desired feature can be only implemented for classes which inherit from classes which provide some hook e.g. as part of the ActiveRecord integration where either `after_create` of `after_initialize` hooks can be used.

Implementation note: can add the hook call here:
https://github.com/geekq/workflow-activerecord/blob/develop/lib/workflow_activerecord/adapters/active_record.rb#L7

**Comment by geekq** [comment]
Played a bit with an implementation in adapters/active_record. The implementation itself is not a problem. But my concerns:

1. changing semantic can surprise / break stuff for people. (minor - can be solved by increasing the dot-release number and documenting in README changelog)
2. adding this feature will probably require additional compensating features like "Make skipping callbacks configurable". Learning from https://github.com/aasm/aasm/pull/326 

So if you need to call `on_myinitial_state_entry` automatically, just use the one-liner suggested by @hinrik !

    after_create :on_myinitial_state_entry

or, depending on [desired effect](https://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html),

    after_initialize :on_myinitial_state_entry
