### ISSUE TITLE
Releases and tags

### ISSUE THREAD

**Issue by stefanahman** [geekq/workflow-activerecord#8]
There are just a single `v0.0.0` tag and a single release. What's the actual gem version?

It is not possible to run `bundle update` to get the latest version.

**Comment by geekq** [comment]
I did not create tags on release so far. Going to use "bundler/gem_tasks" and `rake release` in the future. The latter should automatically create and push tags. Give me one day...

**Comment by geekq** [comment]
```
$ rake release
workflow-activerecord 4.1.4 built to pkg/workflow-activerecord-4.1.4.gem.
Tagged v4.1.4.
Pushed git commits and tags.
Pushed workflow-activerecord 4.1.4 to rubygems.org
```
